version: '3'
services:
  go:
    image: golang:1.13
    container_name: gotodo
    volumes:
      - .:/todoAPI
    working_dir: /todoAPI
    command: ./build.sh
    links:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres
    container_name: postgrestodo
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./db:/postgres
